use_frameworks!

target 'EZLottieExtension_Example' do
  pod 'EZLottieExtension', :path => '../'

  target 'EZLottieExtension_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
